# Generated by Django 4.2.5 on 2023-09-13 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='text',
            field=models.CharField(default=2323, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='greeting',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='greeting',
            name='message',
            field=models.TextField(),
        ),
    ]
